on: push
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "boyroid/teamcity"
          source_branch: "main"
          destination_repo: "boyroid/synchronization-test"
          destination_branch: "main"